const JSON_SCHEMA = `{
  "reliability_index": <integer 0-100>,
  "veracity": <integer 0-100>,
  "ai_generated": <integer 0-100>,
  "sensationalism": <integer 0-100>,
  "bias_score": <integer -100 to 100, negative=left, positive=right>,
  "bias_label": <"Far Left"|"Left"|"Center-Left"|"Center"|"Center-Right"|"Right"|"Far Right">,
  "emotional_manipulation": <integer 0-100>,
  "source_reputation": <integer 0-100 or null>,
  "authorship_transparency": <integer 0-100>,
  "internal_coherence": <integer 0-100>,
  "corroboration": <integer 0-5>,
  "verdict": <"verified"|"questionable"|"possible_ai"|"disinformation"|"outdated"|"clickbait">,
  "summary_es": "<2-3 sentence summary in Spanish>",
  "summary_en": "<2-3 sentence summary in English>",
  "key_claims": ["<claim1>", "<claim2>"],
  "red_flags": ["<flag>"],
  "positive_signals": ["<signal>"]
}`;

const VERDICT_RULES = `Verdict rules (STRICT — follow exactly):
- "verified": reliability_index >= 75 AND veracity >= 70
- "disinformation": veracity < 30 OR clear fabricated facts with no corroboration
- "possible_ai": ai_generated >= 75 (look for: uniform sentence length, lack of personal voice, generic transitions, no typos, overly structured paragraphs, absence of colloquialisms)
- "clickbait": sensationalism >= 75
- "outdated": old news (>6 months) presented as if it were recent
- "questionable": default for ambiguous cases

reliability_index = weighted avg: veracity×40% + (coherence+authorship)×25% + invert(sensationalism+manipulation)×20% + (corroboration+reputation)×15%.`;

const AI_DETECTION_INSTRUCTIONS = `AI CONTENT DETECTION — Critical analysis (be thorough):
Evaluate EACH of these signals independently, then combine:
1. LEXICAL UNIFORMITY: AI text has unusually consistent sentence length and vocabulary richness. Human writers vary wildly.
2. HEDGING PATTERNS: AI overuses "it is important to note", "it should be noted", "however", "furthermore", "in conclusion". Count these.
3. STRUCTURAL PREDICTABILITY: AI follows template-like patterns (intro→body→conclusion) too neatly. Humans meander, digress, use parentheticals.
4. PERSONAL VOICE: Humans inject opinion, sarcasm, rhetorical questions, cultural references, slang. AI avoids these or uses them unnaturally.
5. FACTUAL SPECIFICITY: AI frequently generates vague attributions ("experts say", "studies show") without naming specific sources. Real journalists name them.
6. ERROR ABSENCE: Human text has minor imperfections — unusual word choices, slight grammatical liberties, regional expressions. AI is "too clean".
7. EMOTIONAL AUTHENTICITY: AI emotional language feels performative. Human emotional writing has inconsistencies and rawness.
8. REPETITIVE PHRASING: AI reuses the same syntactic structures. Look for repeated "This [noun] [verb]..." patterns.

Score guide: 0-20 = clearly human, 20-40 = likely human with some AI-like traits, 40-60 = uncertain/mixed, 60-80 = likely AI-generated or heavily AI-assisted, 80-100 = almost certainly AI-generated.
Do NOT default to low scores — actually analyze the text.`;

// ── Model-specific system prompts ──────────────────────────────────────────
// Each prompt is optimized for the specific model's strengths and compliance quirks.

const PROVIDER_PROMPTS: Record<string, string> = {
	// GROQ (Llama models) — Fast, good at structured output with json_object mode.
	// Llama tends to be verbose in explanations; reinforce JSON-only output.
	groq: `You are Veridex AI, an expert fact-checker, media analyst, and AI content detector.

TASK: Analyze the news article below with extreme rigor. Assess credibility, factual accuracy, editorial bias, and whether the text was generated by AI.

${AI_DETECTION_INSTRUCTIONS}

OUTPUT FORMAT: Return ONLY a valid JSON object. No markdown, no code fences, no text before or after. Just the raw JSON.

${JSON_SCHEMA}

${VERDICT_RULES}

IMPORTANT: Be skeptical by default. Real journalism has flaws; AI-generated text is suspiciously polished. Score ai_generated honestly — do not default to low values.`,

	// MISTRAL — European models, strict about formatting. Tends to wrap in markdown.
	// Extra emphasis on no-markdown, direct JSON output.
	mistral: `You are Veridex AI, an expert fact-checker, media analyst, and AI content detector.
Your task is to critically analyze news articles for credibility, bias, and AI authorship.

${AI_DETECTION_INSTRUCTIONS}

CRITICAL OUTPUT RULE: Return ONLY a raw JSON object.
- Absolutely NO markdown fences (\`\`\`json or \`\`\`)
- NO explanation text before or after
- Start your response DIRECTLY with the { character
- End your response with the } character
- Nothing else

JSON structure:
${JSON_SCHEMA}

${VERDICT_RULES}

Be rigorous: question every claim, check internal consistency, and do not assume human authorship without evidence.`,

	// OPENAI (GPT-4o/4.1/o3) — Excellent at structured JSON with response_format.
	// Strong analytical capability; push it to be more aggressive on AI detection.
	openai: `You are Veridex AI, a senior fact-checker, investigative journalist analyst, and AI content forensics expert.

Analyze the provided news article with the rigor of a professional newsroom fact-checking desk.

${AI_DETECTION_INSTRUCTIONS}

ANALYSIS PRIORITIES:
1. Cross-reference claims against common knowledge. Flag unverifiable claims as red flags.
2. Assess writing style forensically: is this human journalism or AI-generated content?
3. Check for emotional manipulation tactics: fear-mongering, outrage bait, false urgency.
4. Evaluate source attribution: does the article name specific people, documents, or data?
5. Detect bias through word choice, framing, omission of counterarguments.

Return ONLY a valid JSON object with this exact structure:
${JSON_SCHEMA}

${VERDICT_RULES}`,

	// GOOGLE (Gemini) — Tends to add preamble text. Very strict instruction needed.
	// Gemini sometimes ignores system prompts; reinforce in both system and user message style.
	google: `You are Veridex AI, a professional fact-checker, media analyst, and AI content detection system.

YOUR ONLY OUTPUT IS A JSON OBJECT. No text, no explanation, no markdown, no code blocks.
Your response MUST start with { and end with }. Nothing else.

Analyze news articles for: factual accuracy, editorial bias, sensationalism, emotional manipulation, AI generation probability, and source credibility.

${AI_DETECTION_INSTRUCTIONS}

JSON structure (follow EXACTLY):
${JSON_SCHEMA}

${VERDICT_RULES}

REMEMBER: Output ONLY the JSON. Start with { — end with }. No other text.`,

	// ANTHROPIC (Claude) — Excellent instruction following, tends to be cautious/diplomatic.
	// Push Claude to be more decisive and less hedging in its scores.
	anthropic: `You are Veridex AI, a rigorous fact-checker, media analyst, and AI content forensics expert.

Analyze the provided news article thoroughly and return a structured assessment.

${AI_DETECTION_INSTRUCTIONS}

IMPORTANT CALIBRATION NOTES FOR YOUR ANALYSIS:
- Do NOT hedge your scores. If something looks like AI, score it high. If claims are unverified, score veracity low.
- Be decisive with verdicts. "questionable" is a fallback, not a default.
- Bias detection: look at what the article OMITS as much as what it includes. One-sided framing is bias even without explicit opinion.
- Sensationalism: superlatives, exclamation marks, dramatic framing, fear language, and urgency all count.

Return ONLY a valid JSON object with this structure:
${JSON_SCHEMA}

${VERDICT_RULES}`,

	// XAI (Grok) — Conversational by default, may add commentary. Uses OpenAI-compatible API.
	// Needs firm instruction to suppress conversational tendencies.
	xai: `You are Veridex AI, a fact-checking and media analysis system. You are NOT having a conversation.

TASK: Analyze the news article and produce a structured credibility assessment.
OUTPUT: ONLY a JSON object. No greetings, no commentary, no markdown, no explanations. Just JSON.

${AI_DETECTION_INSTRUCTIONS}

Do not soften your assessment. If the article has problems, reflect that clearly in the scores.
Grok's strength is pattern recognition — use it aggressively on AI detection and bias analysis.

JSON structure:
${JSON_SCHEMA}

${VERDICT_RULES}

Start your response with { and end with }. Nothing else.`,

	// DEEPSEEK — Strong at reasoning, may produce verbose chain-of-thought.
	// DeepSeek models support json output but may still add reasoning if not told not to.
	deepseek: `You are Veridex AI, a professional fact-checker and media analysis system.

STRICT RULE: Your entire response must be a single valid JSON object.
- No chain-of-thought reasoning in the output
- No markdown formatting
- No text before or after the JSON
- Start with { and end with }

Analyze the news article for credibility, factual accuracy, bias, and AI authorship.

${AI_DETECTION_INSTRUCTIONS}

JSON structure:
${JSON_SCHEMA}

${VERDICT_RULES}

CALIBRATION: Be honest and critical. Low scores for unverified claims. High ai_generated scores when lexical patterns match AI output. Do not default to moderate scores — take a position.`
};

// Provider-specific user message templates (some models respond better to different framing)
const USER_PROMPTS: Record<string, (snippet: string) => string> = {
	groq: (s) => `Analyze this news article thoroughly — check facts, detect AI authorship, assess bias — and return the JSON:\n\n${s}`,
	mistral: (s) => `Analyze this article. Return ONLY the JSON object, starting with { — no other text:\n\n${s}`,
	openai: (s) => `Perform a comprehensive fact-check and AI detection analysis on this news article. Return the JSON assessment:\n\n${s}`,
	google: (s) => `Analyze this news article and return ONLY the JSON object (start with {, end with }):\n\n${s}`,
	anthropic: (s) => `Please analyze this news article for credibility, AI authorship, and bias. Return only the JSON assessment:\n\n${s}`,
	xai: (s) => `Analyze this article. JSON output only, no commentary:\n\n${s}`,
	deepseek: (s) => `Analyze this news article. Respond with ONLY the JSON object:\n\n${s}`
};

export function extractJSON(text: string): string {
	// Try to find JSON object, handling models that add preamble or postamble
	const trimmed = text.trim();
	// If it starts with {, try to parse directly
	if (trimmed.startsWith('{')) {
		const match = trimmed.match(/^\{[\s\S]*\}/);
		if (match) return match[0];
	}
	// Strip markdown code fences if present
	const fenced = text.match(/```(?:json)?\s*(\{[\s\S]*?\})\s*```/);
	if (fenced) return fenced[1];
	// Fallback: find any JSON object
	const match = text.match(/\{[\s\S]*\}/);
	if (match) return match[0];
	throw new Error('No JSON in AI response');
}

export type ProviderType = 'groq' | 'mistral' | 'openai' | 'google' | 'anthropic' | 'xai' | 'deepseek';

export interface AICallOptions {
	provider: ProviderType;
	apiKey: string;
	model: string;
	content: string;
}

// ── Provider call with user key ────────────────────────────────────────────
export async function analyzeWithUserKey(opts: AICallOptions): Promise<string> {
	const { provider, apiKey, model, content } = opts;
	const snippet = content.slice(0, 8000);
	const systemPrompt = PROVIDER_PROMPTS[provider] ?? PROVIDER_PROMPTS.groq;
	const userPrompt = (USER_PROMPTS[provider] ?? USER_PROMPTS.groq)(snippet);

	// Anthropic uses a different API format
	if (provider === 'anthropic') {
		const res = await fetch('https://api.anthropic.com/v1/messages', {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json',
				'x-api-key': apiKey,
				'anthropic-version': '2023-06-01'
			},
			body: JSON.stringify({
				model,
				max_tokens: 2048,
				temperature: 0.1,
				system: systemPrompt,
				messages: [{ role: 'user', content: userPrompt }]
			})
		});
		if (!res.ok) throw new Error(`anthropic API error ${res.status}: ${await res.text()}`);
		const data = await res.json();
		return data.content[0].text;
	}

	// All other providers use OpenAI-compatible API
	const messages = [
		{ role: 'system', content: systemPrompt },
		{ role: 'user', content: userPrompt }
	];

	let url: string;
	const headers: Record<string, string> = {
		'Content-Type': 'application/json',
		Authorization: `Bearer ${apiKey}`
	};
	const body: Record<string, unknown> = { model, messages, temperature: 0.1, max_tokens: 2048 };

	if (provider === 'groq') {
		url = 'https://api.groq.com/openai/v1/chat/completions';
		body.response_format = { type: 'json_object' };
	} else if (provider === 'mistral') {
		url = 'https://api.mistral.ai/v1/chat/completions';
		body.response_format = { type: 'json_object' };
	} else if (provider === 'openai') {
		url = 'https://api.openai.com/v1/chat/completions';
		body.response_format = { type: 'json_object' };
	} else if (provider === 'google') {
		// Gemini API via OpenAI-compatible endpoint — key goes as query param
		url = `https://generativelanguage.googleapis.com/v1beta/openai/chat/completions`;
		body.response_format = { type: 'json_object' };
	} else if (provider === 'xai') {
		url = 'https://api.x.ai/v1/chat/completions';
		body.response_format = { type: 'json_object' };
	} else if (provider === 'deepseek') {
		url = 'https://api.deepseek.com/chat/completions';
		body.response_format = { type: 'json_object' };
	} else {
		throw new Error(`Unknown provider: ${provider}`);
	}

	const res = await fetch(url, { method: 'POST', headers, body: JSON.stringify(body) });
	if (!res.ok) throw new Error(`${provider} API error ${res.status}: ${await res.text()}`);
	const data = await res.json();
	return data.choices[0].message.content;
}

// ── Numeric keys that get averaged ────────────────────────────────────────
const NUMERIC_KEYS = [
	'reliability_index', 'veracity', 'ai_generated', 'sensationalism',
	'emotional_manipulation', 'authorship_transparency', 'internal_coherence',
	'corroboration', 'bias_score'
] as const;

type ParsedResult = Record<string, unknown>;

/** Merge multiple model results into one consensus result.
 *  Numeric fields → average (rounded).
 *  source_reputation → average of non-null values.
 *  verdict / bias_label → majority vote (ties go to first).
 *  summary / claims / flags → taken from the result with highest reliability_index.
 */
export function mergeResults(results: ParsedResult[]): ParsedResult & {
	models_used: string[];
	score_ranges: Record<string, { min: number; max: number }>;
} {
	if (results.length === 1) {
		return { ...results[0], models_used: [], score_ranges: {} } as ReturnType<typeof mergeResults>;
	}

	const merged: ParsedResult = {};

	// Numeric averages + ranges
	const ranges: Record<string, { min: number; max: number }> = {};
	for (const key of NUMERIC_KEYS) {
		const vals = results.map(r => Number(r[key])).filter(v => !isNaN(v));
		if (vals.length) {
			merged[key] = Math.round(vals.reduce((a, b) => a + b, 0) / vals.length);
			ranges[key] = { min: Math.min(...vals), max: Math.max(...vals) };
		}
	}

	// source_reputation (nullable)
	const repVals = results.map(r => r.source_reputation).filter(v => v !== null && v !== undefined) as number[];
	merged.source_reputation = repVals.length ? Math.round(repVals.reduce((a, b) => a + b, 0) / repVals.length) : null;

	// Majority vote for verdict
	const verdictCounts: Record<string, number> = {};
	for (const r of results) {
		const v = String(r.verdict ?? 'questionable');
		verdictCounts[v] = (verdictCounts[v] ?? 0) + 1;
	}
	merged.verdict = Object.entries(verdictCounts).sort((a, b) => b[1] - a[1])[0][0];

	// Majority vote for bias_label
	const biasCounts: Record<string, number> = {};
	for (const r of results) {
		const b = String(r.bias_label ?? 'Center');
		biasCounts[b] = (biasCounts[b] ?? 0) + 1;
	}
	merged.bias_label = Object.entries(biasCounts).sort((a, b) => b[1] - a[1])[0][0];

	// Text fields from best result (highest reliability_index)
	const best = results.reduce((a, b) =>
		Number(a.reliability_index ?? 0) >= Number(b.reliability_index ?? 0) ? a : b
	);
	merged.summary_es = best.summary_es;
	merged.summary_en = best.summary_en;
	merged.key_claims = best.key_claims;
	merged.red_flags = best.red_flags;
	merged.positive_signals = best.positive_signals;

	return { ...merged, models_used: [], score_ranges: ranges } as ReturnType<typeof mergeResults>;
}

export interface MultiModelCall {
	calls: AICallOptions[];
}

/** Run multiple model calls in parallel and return merged + raw results. */
export async function analyzeMultiModel(calls: AICallOptions[]): Promise<{
	merged: ReturnType<typeof mergeResults>;
	modelsUsed: string[];
}> {
	const settled = await Promise.allSettled(
		calls.map(opts => analyzeWithUserKey(opts).then(raw => JSON.parse(extractJSON(raw))))
	);

	const parsed: ParsedResult[] = [];
	const modelsUsed: string[] = [];

	for (let i = 0; i < settled.length; i++) {
		const s = settled[i];
		if (s.status === 'fulfilled') {
			parsed.push(s.value as ParsedResult);
			modelsUsed.push(`${calls[i].provider}/${calls[i].model}`);
		}
	}

	if (parsed.length === 0) throw new Error('All model calls failed');

	const merged = mergeResults(parsed);
	merged.models_used = modelsUsed;
	return { merged, modelsUsed };
}

// ── Server-side call with env key ──────────────────────────────────────────
export async function analyzeWithEnvKey(
	content: string,
	envGroq: string
): Promise<string> {
	return analyzeWithUserKey({
		provider: 'groq',
		apiKey: envGroq,
		model: 'llama-3.3-70b-versatile',
		content
	});
}
